env.name :  "uat"

email:
  fromAddress :  "svc-integrations@chargepoint.com"
  toAddress: "svc-integrations@chargepoint.com"
  subject :  "INFO: Custom Application Notification"

box.file.link :  "https://chargepoint-sandbox.app.box.com/file/"

#CloudHub
cloudhub:
  username: "svc-mulesoft"
  password: "![qAIo0vw8XjL6xPNmObWK3N8yKPyXkzsFRj061f+kbV4=]"

ftp:
  flex:
    username: "![c9hcDIDaaVVNTW1+V5tw9A==]"
    password: "![aklfEH9KpGfkkGXhpjF2nw==]"
    port: "21"
    host: "ftpam.flextronics.com"
    
#AWS Config
aws:
  cpit:
    accessKey: "AKIA6OBDM36ELEEHKBPM"
    secretKey: "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"
    region: "us-west-2"
    role: "arn:aws:iam::992211689352:role/cp-qa-marketo-driver-sync-mulesoft-operator"
  cpbiz:
    accessKey: "AKIAV534ORQWKA2HBUG7"
    secretKey: "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"
    region: "us-west-2"
    role: "arn:aws:iam::992211689352:role/cp-qa-marketo-driver-sync-mulesoft-operator"
  cpeng:
    accessKey: "AKIA6OBDM36ELEEHKBPM"
    secretKey: "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"
    region: "us-west-2"
    role: "arn:aws:iam::992211689352:role/cp-qa-marketo-driver-sync-mulesoft-operator"

#AWS DynamoDB Config
dynamo:
  bizapps:
    accessKey: "AKIAUK5V3L2GCBZTB2M6"
    secretKey: "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"
    region: "US_WEST_2"

#OSPC Configuration
ospc:
  username: "pratik.singh@trinamix.com"
  password: "Trinamix123"
  host: "fa-epsh-test-saasfaprod1.fa.ocs.oraclecloud.com"
  
#AWS Redshift Config

redshift:
  url: "jdbc:redshift://cpedwprod.ctnq69hlrn0r.us-west-2.redshift.amazonaws.com:5439/cpedwprod"
  username: "svc_integrations"
  password: "![2dHDiO49/J1B8xGvBfDCLV3bKat075Gx5PoUXYKjmG0=]"