
env.name : "prod"

email:
  fromAddress: "svc-integrations@chargepoint.com"
  toAddress: "svc-integrations@chargepoint.com"
  subject : "INFO: Custom Application Notification"

box.file.link : "https://chargepoint.app.box.com/file/"

#CloudHub
cloudhub:
  username: "svc-mulesoft"
  password: "![LL5ai8t4AeYCtxBoyz3IdGR0h6zgsNG3ZoBfdM57bPA=]"

ftp:
  flex:
    username: "![vnyPJl/7bPy6pIgkrfDBpg==]"
    password: "![US2Fekkv52dAPChLk4T3Qw==]"
    port: "21"
    host: "ftpam.flextronics.com"
    

#AWS Config
aws:
  cpit:
    accessKey: "![HPw+9W4q1AlKNScTVtGSU4NnFHOzkcgASKolC7AEdEk=]"
    secretKey: "![CqK4t4s43+V5xIcc51ipWRJULgZe1SW4ZSLBe7Nw6LnRJSRdgirdMz1Coc9Iq+mN]"
    region: "us-west-2"
    role: "![SNAUAFwl1Wx4f2zW9jQ1V719RwdXCQZ7JPZ9Mb3gMdtu1fQNN3iXe5G7hZDDuREgRkIC97liz64alrSemBNCAw==]"
  cpbiz:
    accessKey: "AKIAV534ORQWKA2HBUG7"
    secretKey: "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"
    region: "us-west-2"
    role: "arn:aws:iam::992211689352:role/cp-qa-marketo-driver-sync-mulesoft-operator"
  cpeng:
    accessKey: "AKIA6OBDM36ELEEHKBPM"
    secretKey: "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"
    region: "us-west-2"
    role: "arn:aws:iam::992211689352:role/cp-qa-marketo-driver-sync-mulesoft-operator"
    
#AWS DynamoDB Config
dynamo:
  bizapps:
    accessKey: "AKIAUK5V3L2GCBZTB2M6"
    secretKey: "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"
    region: "US_WEST_2"
    
#AWS Redshift Config

redshift:
  url: "jdbc:redshift://cpedwprod.ctnq69hlrn0r.us-west-2.redshift.amazonaws.com:5439/cpedwprod"
  username: "svc_integrations"
  password: "![2dHDiO49/J1B8xGvBfDCLV3bKat075Gx5PoUXYKjmG0=]"