#HTTP Listener Configuration
http:
  host: 0.0.0.0
  port: "8081"
  responseTimeout: "900000"

#SMTP Configuration
smtp:
  server: "chargepoint-com.mail.protection.outlook.com"
  port: "25"
  email: "svc-integrations@chargepoint.com"

#BOX Configuration
box:
  host: "api.box.com"
  basepath: "2.0"
  upload.host: "upload.box.com"
  upload.basepath: "api/2.0"


#Redshift Driver Config

redshift:
  driverClassName: "com.amazon.redshift.jdbc42.Driver"
  rmaHistoryQuery: "select week,tick_num,mac,sn,evse_id,model_int,model_detail,issue,sent,rma_num,fso_num,subject,dd_by,tick_type,salesops_process_time,cause_code,assignee,invalid,invalid_detail,part_num,part_sn,index_id from reporting_support.na_hist_rma"

#CloudHub Config
cloudhub:
  environment: "c948f19f-8593-482f-bdf6-47d022d5823b"
  domain: "sys-common-us-int-qa"

#OSPC Configuration
ospc:
  path: "fscmRestApi/resources/11.13.18.05/erpintegrations"
  responseTimeout: "30000"
  connectionIdleTimeout: "30000"
  wsc.timeToLive: "1000"
  wsc.operation: "GenericSoapOperation"
  getsearchresult:
    docAccount: "scm$/planningDataLoader$/export$"
    docTitle: "ReleaseToExternalSource"
  sourceSystem: "CPI"

#Marketo Configuration
marketo:
  responseTimeout: "50000"
  connectionIdleTimeout: "50000"
  bulk.basepath: "/bulk/v1"
  oauth.basepath: "/identity"
  api.maxretries: "3"
  reconnect.frequency: "240000"
  reconnect.count: "5"


#DynamoDB Batch Put Items Types
dynamoDb:
  keyTypes:
    string: "S"
    number: "N"
    binary: "B"
    boolean: "BOOL"
    null: "NULL"
    map: "M"
    list: "L"
    string-set: "SS"
    number-set: "NS"
    binary-set: "BS"
  operators: 
    eq: "="
    ne: "!="
    gt: ">"
    lt: "<"
    ge: ">="
    le: "<="
  batchSize: "25"
  
dynamo:  
  reseveredKeys:
    abort : "ABORT"
    absolute : "ABSOLUTE"
    action : "ACTION"
    add : "ADD"
    after : "AFTER"
    agent : "AGENT"
    aggregate : "AGGREGATE"
    all : "ALL"
    allocate : "ALLOCATE"
    alter : "ALTER"
    analyze : "ANALYZE"
    and : "AND"
    any : "ANY"
    archive : "ARCHIVE"
    are : "ARE"
    array : "ARRAY"
    as : "AS"
    asc : "ASC"
    ascii : "ASCII"
    asensitive : "ASENSITIVE"
    assertion : "ASSERTION"
    asymmetric : "ASYMMETRIC"
    at : "AT"
    atomic : "ATOMIC"
    attach : "ATTACH"
    attribute : "ATTRIBUTE"
    auth : "AUTH"
    authorization : "AUTHORIZATION"
    authorize : "AUTHORIZE"
    auto : "AUTO"
    avg : "AVG"
    back : "BACK"
    backup : "BACKUP"
    base : "BASE"
    batch : "BATCH"
    before : "BEFORE"
    begin : "BEGIN"
    between : "BETWEEN"
    bigint : "BIGINT"
    binary : "BINARY"
    bit : "BIT"
    blob : "BLOB"
    block : "BLOCK"
    both : "BOTH"
    breadth : "BREADTH"
    bucket : "BUCKET"
    bulk : "BULK"
    by : "BY"
    byte : "BYTE"
    call : "CALL"
    called : "CALLED"
    calling : "CALLING"
    capacity : "CAPACITY"
    cascade : "CASCADE"
    cascaded : "CASCADED"
    case : "CASE"
    cast : "CAST"
    catalog : "CATALOG"
    char : "CHAR"
    character : "CHARACTER"
    check : "CHECK"
    class : "CLASS"
    clob : "CLOB"
    close : "CLOSE"
    cluster : "CLUSTER"
    clustered : "CLUSTERED"
    clustering : "CLUSTERING"
    clusters : "CLUSTERS"
    coalesce : "COALESCE"
    collate : "COLLATE"
    collation : "COLLATION"
    ordinality : "ORDINALITY"
    other : "OTHER"
    others : "OTHERS"
    out : "OUT"
    outer : "OUTER"
    output : "OUTPUT"
    over : "OVER"
    overlaps : "OVERLAPS"
    override : "OVERRIDE"
    owner : "OWNER"
    pad : "PAD"
    parallel : "PARALLEL"
    parameter : "PARAMETER"
    parameters : "PARAMETERS"
    partial : "PARTIAL"
    partition : "PARTITION"
    partitioned : "PARTITIONED"
    partitions : "PARTITIONS"
    path : "PATH"
    percent : "PERCENT"
    percentile : "PERCENTILE"
    permission : "PERMISSION"
    permissions : "PERMISSIONS"
    pipe : "PIPE"
    pipelined : "PIPELINED"
    plan : "PLAN"
    pool : "POOL"
    position : "POSITION"
    precision : "PRECISION"
    prepare : "PREPARE"
    preserve : "PRESERVE"
    primary : "PRIMARY"
    prior : "PRIOR"
    private : "PRIVATE"
    privileges : "PRIVILEGES"
    procedure : "PROCEDURE"
    processed : "PROCESSED"
    project : "PROJECT"
    projection : "PROJECTION"
    property : "PROPERTY"
    provisioning : "PROVISIONING"
    public : "PUBLIC"
    put : "PUT"
    query : "QUERY"
    quit : "QUIT"
    quorum : "QUORUM"
    raise : "RAISE"
    random : "RANDOM"
    range : "RANGE"
    rank : "RANK"
    raw : "RAW"
    read : "READ"
    reads : "READS"
    real : "REAL"
    rebuild : "REBUILD"
    record : "RECORD"
    recursive : "RECURSIVE"
    reduce : "REDUCE"
    ref : "REF"
    reference : "REFERENCE"
    references : "REFERENCES"
    referencing : "REFERENCING"
    regexp : "REGEXP"
    region : "REGION"
    reindex : "REINDEX"
    relative : "RELATIVE"
    release : "RELEASE"
    remainder : "REMAINDER"
    rename : "RENAME"
    repeat : "REPEAT"
    replace : "REPLACE"
    request : "REQUEST"
    reset : "RESET"
    resignal : "RESIGNAL"
    resource : "RESOURCE"
    response : "RESPONSE"
    restore : "RESTORE"
    restrict : "RESTRICT"
    result : "RESULT"
    return : "RETURN"
    returning : "RETURNING"
    returns : "RETURNS"
    reverse : "REVERSE"
    revoke : "REVOKE"
    right : "RIGHT"
    role : "ROLE"
    roles : "ROLES"
    rollback : "ROLLBACK"
    rollup : "ROLLUP"
    routine : "ROUTINE"
    row : "ROW"
    rows : "ROWS"
    rule : "RULE"
    rules : "RULES"
    sample : "SAMPLE"
    satisfies : "SATISFIES"
    save : "SAVE"
    savepoint : "SAVEPOINT"
    scan : "SCAN"
    schema : "SCHEMA"
    scope : "SCOPE"
    scroll : "SCROLL"
    search : "SEARCH"
    second : "SECOND"
    section : "SECTION"
    segment : "SEGMENT"
    segments : "SEGMENTS"
    select : "SELECT"
    self : "SELF"
    semi : "SEMI"
    sensitive : "SENSITIVE"
    separate : "SEPARATE"
    sequence : "SEQUENCE"
    serializable : "SERIALIZABLE"
    session : "SESSION"
    set : "SET"
    sets : "SETS"
    shard : "SHARD"
    share : "SHARE"
    shared : "SHARED"
    short : "SHORT"
    show : "SHOW"
    signal : "SIGNAL"
    similar : "SIMILAR"
    size : "SIZE"
    skewed : "SKEWED"
    smallint : "SMALLINT"
    snapshot : "SNAPSHOT"
    some : "SOME"
    source : "SOURCE"
    space : "SPACE"
    spaces : "SPACES"
    sparse : "SPARSE"
    specific : "SPECIFIC"
    specifictype : "SPECIFICTYPE"
    split : "SPLIT"
    sql : "SQL"
    sqlcode : "SQLCODE"
    sqlerror : "SQLERROR"
    sqlexception : "SQLEXCEPTION"
    sqlstate : "SQLSTATE"
    sqlwarning : "SQLWARNING"
    start : "START"
    state : "STATE"
    static : "STATIC"
    status : "STATUS"
    storage : "STORAGE"
    store : "STORE"
    stored : "STORED"
    stream : "STREAM"
    string : "STRING"
    struct : "STRUCT"
    style : "STYLE"
    sub : "SUB"
    submultiset : "SUBMULTISET"
    subpartition : "SUBPARTITION"
    substring : "SUBSTRING"
    subtype : "SUBTYPE"
    sum : "SUM"
    super : "SUPER"
    symmetric : "SYMMETRIC"
    synonym : "SYNONYM"
    system : "SYSTEM"
    table : "TABLE"
    tablesample : "TABLESAMPLE"
    temp : "TEMP"
    temporary : "TEMPORARY"
    terminated : "TERMINATED"
    text : "TEXT"
    than : "THAN"
    then : "THEN"
    throughput : "THROUGHPUT"
    time : "TIME"
    timestamp : "TIMESTAMP"
    timezone : "TIMEZONE"
    tinyint : "TINYINT"
    to : "TO"
    token : "TOKEN"
    total : "TOTAL"
    touch : "TOUCH"
    trailing : "TRAILING"
    transaction : "TRANSACTION"
    transform : "TRANSFORM"
    translate : "TRANSLATE"
    translation : "TRANSLATION"
    treat : "TREAT"
    trigger : "TRIGGER"
    trim : "TRIM"
    truncate : "TRUNCATE"
    ttl : "TTL"
    tuple : "TUPLE"
    type : "TYPE"
    under : "UNDER"
    undo : "UNDO"
    union : "UNION"
    unique : "UNIQUE"
    unit : "UNIT"
    unknown : "UNKNOWN"
    unlogged : "UNLOGGED"
    unnest : "UNNEST"
    unprocessed : "UNPROCESSED"
    unsigned : "UNSIGNED"
    until : "UNTIL"
    update : "UPDATE"
    upper : "UPPER"
    url : "URL"
    usage : "USAGE"
    use : "USE"
    user : "USER"
    users : "USERS"
    using : "USING"
    uuid : "UUID"
    vacuum : "VACUUM"
    value : "VALUE"
    valued : "VALUED"
    values : "VALUES"
    varchar : "VARCHAR"
    variable : "VARIABLE"
    variance : "VARIANCE"
    varint : "VARINT"
    varying : "VARYING"
    view : "VIEW"
    views : "VIEWS"
    virtual : "VIRTUAL"
    void : "VOID"
    wait : "WAIT"
    when : "WHEN"
    whenever : "WHENEVER"
    where : "WHERE"
    while : "WHILE"
    window : "WINDOW"
    with : "WITH"
    within : "WITHIN"
    without : "WITHOUT"
    work : "WORK"
    wrapped : "WRAPPED"
    write : "WRITE"
    year : "YEAR"
    zone : "ZONE"
    collection : "COLLECTION"
    column : "COLUMN"
    columns : "COLUMNS"
    combine : "COMBINE"
    comment : "COMMENT"
    commit : "COMMIT"
    compact : "COMPACT"
    compile : "COMPILE"
    compress : "COMPRESS"
    condition : "CONDITION"
    conflict : "CONFLICT"
    connect : "CONNECT"
    connection : "CONNECTION"
    consistency : "CONSISTENCY"
    consistent : "CONSISTENT"
    constraint : "CONSTRAINT"
    constraints : "CONSTRAINTS"
    constructor : "CONSTRUCTOR"
    consumed : "CONSUMED"
    continue : "CONTINUE"
    convert : "CONVERT"
    copy : "COPY"
    corresponding : "CORRESPONDING"
    count : "COUNT"
    counter : "COUNTER"
    create : "CREATE"
    cross : "CROSS"
    cube : "CUBE"
    current : "CURRENT"
    cursor : "CURSOR"
    cycle : "CYCLE"
    data : "DATA"
    database : "DATABASE"
    date : "DATE"
    datetime : "DATETIME"
    day : "DAY"
    deallocate : "DEALLOCATE"
    dec : "DEC"
    decimal : "DECIMAL"
    declare : "DECLARE"
    default : "DEFAULT"
    deferrable : "DEFERRABLE"
    deferred : "DEFERRED"
    define : "DEFINE"
    defined : "DEFINED"
    definition : "DEFINITION"
    delete : "DELETE"
    delimited : "DELIMITED"
    depth : "DEPTH"
    deref : "DEREF"
    desc : "DESC"
    describe : "DESCRIBE"
    descriptor : "DESCRIPTOR"
    detach : "DETACH"
    deterministic : "DETERMINISTIC"
    diagnostics : "DIAGNOSTICS"
    directories : "DIRECTORIES"
    disable : "DISABLE"
    disconnect : "DISCONNECT"
    distinct : "DISTINCT"
    distribute : "DISTRIBUTE"
    do : "DO"
    domain : "DOMAIN"
    double : "DOUBLE"
    drop : "DROP"
    dump : "DUMP"
    duration : "DURATION"
    dynamic : "DYNAMIC"
    each : "EACH"
    element : "ELEMENT"
    else : "ELSE"
    elseif : "ELSEIF"
    empty : "EMPTY"
    enable : "ENABLE"
    end : "END"
    equal : "EQUAL"
    equals : "EQUALS"
    error : "ERROR"
    escape : "ESCAPE"
    escaped : "ESCAPED"
    eval : "EVAL"
    evaluate : "EVALUATE"
    exceeded : "EXCEEDED"
    except : "EXCEPT"
    exception : "EXCEPTION"
    exceptions : "EXCEPTIONS"
    exclusive : "EXCLUSIVE"
    exec : "EXEC"
    execute : "EXECUTE"
    exists : "EXISTS"
    exit : "EXIT"
    explain : "EXPLAIN"
    explode : "EXPLODE"
    export : "EXPORT"
    expression : "EXPRESSION"
    extended : "EXTENDED"
    external : "EXTERNAL"
    extract : "EXTRACT"
    fail : "FAIL"
    family : "FAMILY"
    fetch : "FETCH"
    fields : "FIELDS"
    file : "FILE"
    filter : "FILTER"
    filtering : "FILTERING"
    final : "FINAL"
    finish : "FINISH"
    first : "FIRST"
    fixed : "FIXED"
    flattern : "FLATTERN"
    float : "FLOAT"
    for : "FOR"
    force : "FORCE"
    foreign : "FOREIGN"
    format : "FORMAT"
    forward : "FORWARD"
    found : "FOUND"
    free : "FREE"
    from : "FROM"
    full : "FULL"
    function : "FUNCTION"
    functions : "FUNCTIONS"
    general : "GENERAL"
    generate : "GENERATE"
    get : "GET"
    glob : "GLOB"
    global : "GLOBAL"
    go : "GO"
    goto : "GOTO"
    grant : "GRANT"
    greater : "GREATER"
    group : "GROUP"
    grouping : "GROUPING"
    handler : "HANDLER"
    hash : "HASH"
    have : "HAVE"
    having : "HAVING"
    heap : "HEAP"
    hidden : "HIDDEN"
    hold : "HOLD"
    hour : "HOUR"
    identified : "IDENTIFIED"
    identity : "IDENTITY"
    if : "IF"
    ignore : "IGNORE"
    immediate : "IMMEDIATE"
    import : "IMPORT"
    in : "IN"
    including : "INCLUDING"
    inclusive : "INCLUSIVE"
    increment : "INCREMENT"
    incremental : "INCREMENTAL"
    index : "INDEX"
    indexed : "INDEXED"
    indexes : "INDEXES"
    indicator : "INDICATOR"
    infinite : "INFINITE"
    initially : "INITIALLY"
    inline : "INLINE"
    inner : "INNER"
    innter : "INNTER"
    inout : "INOUT"
    input : "INPUT"
    insensitive : "INSENSITIVE"
    insert : "INSERT"
    instead : "INSTEAD"
    int : "INT"
    integer : "INTEGER"
    intersect : "INTERSECT"
    interval : "INTERVAL"
    into : "INTO"
    invalidate : "INVALIDATE"
    is : "IS"
    isolation : "ISOLATION"
    item : "ITEM"
    items : "ITEMS"
    iterate : "ITERATE"
    join : "JOIN"
    key : "KEY"
    keys : "KEYS"
    lag : "LAG"
    language : "LANGUAGE"
    large : "LARGE"
    last : "LAST"
    lateral : "LATERAL"
    lead : "LEAD"
    leading : "LEADING"
    leave : "LEAVE"
    left : "LEFT"
    length : "LENGTH"
    less : "LESS"
    level : "LEVEL"
    like : "LIKE"
    limit : "LIMIT"
    limited : "LIMITED"
    lines : "LINES"
    list : "LIST"
    load : "LOAD"
    local : "LOCAL"
    localtime : "LOCALTIME"
    localtimestamp : "LOCALTIMESTAMP"
    location : "LOCATION"
    locator : "LOCATOR"
    lock : "LOCK"
    locks : "LOCKS"
    log : "LOG"
    loged : "LOGED"
    long : "LONG"
    loop : "LOOP"
    lower : "LOWER"
    map : "MAP"
    match : "MATCH"
    materialized : "MATERIALIZED"
    max : "MAX"
    maxlen : "MAXLEN"
    member : "MEMBER"
    merge : "MERGE"
    method : "METHOD"
    metrics : "METRICS"
    min : "MIN"
    minus : "MINUS"
    minute : "MINUTE"
    missing : "MISSING"
    mod : "MOD"
    mode : "MODE"
    modifies : "MODIFIES"
    modify : "MODIFY"
    module : "MODULE"
    month : "MONTH"
    multi : "MULTI"
    multiset : "MULTISET"
    name : "NAME"
    names : "NAMES"
    national : "NATIONAL"
    natural : "NATURAL"
    nchar : "NCHAR"
    nclob : "NCLOB"
    new : "NEW"
    next : "NEXT"