#%RAML 1.0 DataType
description: Datatypes for write operation
type: object
properties:
  
  sourcePath:
    required: true
    type: string
  targetPath:
    required: true
    type: string
  account:
    required: true
    type: string
