#%RAML 1.0 DataType
description: Datatypes for read and list operations
type: object
properties:
  
  sourcePath:
    required: true
    type: string
  account: 
    required: true
    type: string
  

