#%RAML 1.0 DataType
description: Datatype for updatinf the uspc doc info request
type: object
properties:
 id:
  type: string
  required: true
  description: Update doc info request Id.
 doc_name:
  type: string
  required: true
  description: Document Name.
 comments:
  type: string
  required: true
  description: Comments.