#%RAML 1.0 DataType
properties:
  table_name: 
    type: string
    required: true
    example: "screen"
    description:  Name of the table
  account_id:
    type: string
    required: true
    example: "bizapps"
    description:  Account to be used in configuration
  attributes_to_get: 
    description: Allows you to retrieve attribute of type List or Map however it cannot retrieve individual elements within a List or a Map.
    type: array
    required: false
    example: ["firstname", "lastname"]
  conditional_operator: 
    type: string
    required: false
    example: "AND or OR"
    description: A logical operator to apply to the conditions in a Expected, QueryFilter or ScanFilter map:AND - If all of the conditions evaluate to true, then the entire map evaluates to true.OR - If at least one of the conditions evaluate to true, then the entire map evaluates to true.If you omit ConditionalOperator, then AND is the default.
  consistent_read:
    type: boolean
    required: false
    example:  true
    description: A Boolean value that determines the read consistency model during the scan. if false, then the data returned from Scan might not contain the results from other recently completed write operations (PutItem, UpdateItem, or DeleteItem). If true, then all of the write operations that completed before the Scan began are guaranteed to be contained in the Scan response. 
  exclusive_start_key: 
    type: object
    required: false
    example: {"abc": {"BOOL": true}}
    description: The primary key of the first item that this operation will evaluate. Use the value that was returned for LastEvaluatedKey in the previous operation. The data type for ExclusiveStartKey must be String, Number or Binary. No set data types are allowed. In a parallel scan, a Scan request that includes ExclusiveStartKey must specify the same segment whose previous Scan returned the corresponding value of LastEvaluatedKey.
  filter_attributes:
    required: false
    example: {"tran_purpose_code": { "operator":"eq","data_type": "string","is_reserved_key":false,"value":"06"}}
    type: object
  index_name: 
    type: string
    required: false
    example: "2" 
    description: The name of a secondary index to scan. This index can be any local secondary index or global secondary index. Note that if you use the IndexName parameter, you must also provide TableName.
  limit: 
    type: number
    required: false
    example: 3 
    description: The maximum number of items to evaluate (not necessarily the number of matching items). If DynamoDB processes the number of items up to the limit while processing the results, it stops the operation and returns the matching values up to that point, and a key in LastEvaluatedKey to apply in a subsequent operation, so that you can pick up where you left off. Also, if the processed dataset size exceeds 1 MB before DynamoDB reaches this limit, it stops the operation and returns the matching values up to the limit, and a key in LastEvaluatedKey to apply in a subsequent operation to continue the operation
  projection_expression:
    type: string
    required: false
    example: "firstname,lastname" 
    description: A string that identifies one or more attributes to retrieve from the specified table or index. These attributes can include scalars, sets, or elements of a JSON document. The attributes in the expression must be separated by commas.  
  return_consumed_capacity:
    type: string
    required: false
    example: "INDEXES | TOTAL | NONE"
    description: Determines the level of detail about provisioned throughput consumption that is returned in the response. INDEXES - The response includes the aggregate ConsumedCapacity for the operation, together with ConsumedCapacity for each table and secondary index that was accessed. TOTAL - The response includes only the aggregate ConsumedCapacity for the operation. NONE - No ConsumedCapacity details are included in the response.
  segment:
    type: number
    required: false
    example: 0 
    description: For a parallel Scan request, Segment identifies an individual segment to be scanned by an application worker.
  select:
    type: string
    required: false
    example: "ALL_ATTRIBUTES | ALL_PROJECTED_ATTRIBUTES | SPECIFIC_ATTRIBUTES | COUNT"
    description: The attributes to be returned in the result. You can retrieve all item attributes, specific item attributes, the count of matching items, or in the case of an index, some or all of the attributes projected into the index.
  total_segments: 
    type: number
    required: false
    example: 1
    description: For a parallel Scan request, TotalSegments represents the total number of segments into which the Scan operation will be divided. The value of TotalSegments corresponds to the number of application workers that will perform the parallel scan. For example, if you want to use four application threads to scan a table or an index, specify a TotalSegments value of 4.    
  conditional_filter: 
    type: object
    required: false
    example: {}
    description: Used for applying conditional filters