#%RAML 1.0 ResourceType
post:
  body:
    application/json:
      type: <<data-request-type>>
      example: <<data-request-example>>  
  responses:
    200:
      body:
        application/json:
          type: <<response-200-type>>
          example: <<response-200-example>>  
    400:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse400.json
    404:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse404.json
    405:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse405.json
    406:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse406.json
    415:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse415.json
    500:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse500.json
    503:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse503.json
    504:
      body:
        application/json:
          type: <<error-response>>
          example: !include ../examples/error/errorExampleResponse504.json