{
  "headers": {
    "region": "US",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.26.3",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "902d4c1b-1079-4d55-b2d0-9cd2b8c02538",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "325"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/v1/marketo/bulk/export/leads",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/v1/marketo/bulk/export/leads",
  "listenerPath": "/api/*",
  "relativePath": "/api/v1/marketo/bulk/export/leads",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/v1/marketo/bulk/export/leads",
  "rawRequestPath": "/api/v1/marketo/bulk/export/leads",
  "remoteAddress": "/127.0.0.1:60272",
  "requestPath": "/api/v1/marketo/bulk/export/leads"
}