{
  "bucketName": "cpedwqa",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "application/octet-stream",
  "key": "text1.txt",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "versionId": "XqRpdfF0wcre26Tv.8CDEO2uFgrp0XGY",
  "sseAwsKmsKeyId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "etag": "6ccb8fac358fea58732ed8ffec85b9f5",
  "contentLength": 26,
  "lastModified": |2020-08-31T11:02:23|,
  "userMetadata": {},
  "redirectLocation": null
}