{
  "headers": {
    "content-type": "application/json",
    "access_token": "0CJhIsw7WFrhsj59Fh7kyBAMKQgr3BFp",
    "folder_id": "0",
    "user-agent": "PostmanRuntime/7.25.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "87ffaddc-b22e-4a81-9b89-d0481c956b5b",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "19768"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/box/upload-file",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/box/upload-file",
  "listenerPath": "/api/*",
  "relativePath": "/api/box/upload-file",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/box/upload-file",
  "rawRequestPath": "/api/box/upload-file",
  "remoteAddress": "/127.0.0.1:51264",
  "requestPath": "/api/box/upload-file"
}