#%RAML 1.0 Library


types:           
  file_document_response: 
      description: Inbound data response schema
      type: array
      items:
        properties:
         id:
          type: string
          required: false
          description: Uploaded data request Id
         file_name:
          type: string
          required: false
          description: File Name
         original_name:
          type: string
          required: false
          description: File Original Name
         format:
          type: string
          required: false
          description: File Format
         extension:
          type: string
          required: false
          description: File Extension
         file_size:
          type: string
          required: false
          description: File size
         content:
          type: string
          required: false
          description: The content of the file in Base64 encoded format.