#%RAML 1.0 Library


types:           
  job_execution_response: 
      type: object
      description: Inbound data response schema
      properties:
       request_id:
        type: string
        required: false
        description: Uploaded data request Id
       status:
        type: string
        required: false
        description: File Status
       document_content:
        type: string
        required: false
        description: The content of the file in Base64 encoded format.