#%RAML 1.0 Library
types:           
  export_job_status_response: 
      type: object
      description: Export Job Status response schema
      properties:
       request_id:
        type: string
        required: false
        description: Request Id
       result:
        type: array
        description: Result of the request
        items:
         properties: 
           
           export_id:
            type: string
            required: false
            description: Export Id
           status:
            type: string
            required: false
            description: status of the batch
           format:
            type: string
            required: false
            description: Format of the file
           created_at:
            type: string
            required: false
            description: Created Date and Time
           queued_at:
            type: string
            required: false
            description: Queued Date and Time
           started_at:
            type: string
            required: false
            description: Started Date and Time
           finished_at:
            type: string
            required: false
            description: Finished Date and Time
           number_of_records:
            type: number
            required: false
            description: No Of Records
           file_size:
            type: number
            required: false
            description: File Size
           file_check_sum:
            type: string
            required: false
            description: SHA-256 hash of exported file
       success:
          type: boolean
          required: false
          description: Whether the request succeeded

