#%RAML 1.0 Library


types:           
  import_marketo_request: 
      type: object
      description: Import Marketo request schema
      properties:
       file_name:
        type: string
        required: true
        description: FileName with extension
       format:
        enum: ["CSV","TSV","SSV"]
        required: true
        description: File format.
       content_data:
         type: string
         required: true
         description: Accept GZIP Base64 format as content