#%RAML 1.0 Library


types:           
  inboundData_request: 
      type: object
      description: Inbound data schema
      properties:
       document_content:
        type: string
        minLength: 1
        required: true
        description: The content of the file in Base64 encoded format.
       content_type:
        type: string
        minLength: 1
        required: true
        description: The type of content within a data file to be processed by the OSPC Integration Service.
       file_name:
        type: string
        minLength: 1
        required: true
        description: The name of the data file to be processed by the OSPC Integration Service.
       collection_type:
        type: number
        enum: [1,2]
        required: true
        description: 1-Targeted,2-Net Change.
       document_id:
         type: string
         required: false
         description: Document Id
       notification_code:
        type: string
        required: false
        description: The two-digit code that determines the notification type and when the notification should be sent.
       interface_details:
        type: string
        required: false
        description: Interface Details.
       import_option:
        type: string
        enum: ["Y","N"]
        required: false
        description: Import Option. Y-Yes and N-No

