#%RAML 1.0 Library


types:           
  export_activity_marketo_request: 
      type: object
      description: Export ACtivity Marketo request schema
      properties:
       column_header_names:
        type: object
        required: false
        description: Allows setting the names of column headers in the returned file. 
       format:
        enum: ["CSV","TSV","SSV"]
        required: false
        description: File format.
       fields:
         type: array
         required: false
         description: array of strings containing field values
       filter:
         type: object
         required: true
         description: Filter applied to the extract job.	Accepts an array of filters.  Exactly one createdAt filter must be included in the array.  An optional activityTypeIds filter may be included
         properties:
           created_at:
            type: object
            required: true
            description: Accepts a JSON object with the members start_at and end_at.The range must be 31 days or fewer.
           activity_type_ids:
            type: array
            required: false
            description: The value should be an array of integers, corresponding to the desired activity types.
           
            