#%RAML 1.0 Library


types:           
  import_marketo_response: 
      type: object
      description: Import Marketo response schema
      properties:
       request_id:
        type: string
        required: false
        description: Request Id
       result:
        type: array
        description: Result of the request
        items:
         properties: 
           batch_id:
            type: number
            required: true
            description: Unique integer id of the import batch
           import_id:
            type: string
            required: false
            description: Import Id
           status:
            type: string
            required: false
            description: status of the batch
       success:
          type: boolean
          required: false
          description: Whether the request succeeded